language: cpp
compiler:
    - clang
script: scons apps samples
branches:
    only:
        - master
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost1.53-all-dev libssl-dev libcurl4-openssl-dev
notifications:
    email:
        on_success: change
        on_failure: always
