---
- name: Create nodes configuration directory
  file: dest={{ nodes_config_root }} state=directory

- name: Create CA directory
  file: dest={{ ca_root }} state=directory

- name: Create nodes scripts directory
  file: dest={{ scripts_root }} state=directory

- name: Create nodes certificates and private keys
  command: openssl req -new -nodes -x509 -subj "/CN={{ item.name }}" -days 3650 -keyout {{ nodes_config_root }}/{{ item.name }}.key -out {{ nodes_config_root }}/{{ item.name }}.crt -extensions v3_ca creates={{ nodes_config_root }}/{{ item.name }}.crt
  with_items: freelan_nodes

- name: Create nodes configuration files 
  template: src=configuration.conf dest={{ nodes_config_root }}/{{ item.name }}.conf
  with_items: freelan_nodes
